# Generated by Django 2.1.3 on 2019-01-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=False)),
                ('bmi', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('insulin', models.IntegerField(default=0)),
                ('func', models.FloatField(default=0)),
                ('blood_sugar', models.FloatField(default=0)),
                ('ifpreg', models.BooleanField(default=False)),
                ('pregancy', models.IntegerField(default=0)),
                ('blood_pressure', models.FloatField(default=0)),
                ('skin_thickness', models.FloatField(default=0)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
